baseURL = '/'
copyright = "Made by Michael Hahn with <a href='https://github.com/timothygebhard/barks'>barks</a>."
languageCode = 'en-us'
title = 'Michael Hahn'
theme = 'barks'

[params]
    [params.social.email]
        name = "E-Mail"
        class = "fas fa-envelope"
        url = "mailto:michael.hahn@uni-tuebingen.de"
        weight = 1
    [params.social.github]
        name = "GitHub"
        class = "fab fa-github"
        url = "https://github.com/hahnmic"
        weight = 2
    [params.social.google_scholar]
        name = "Google Scholar"
        class = "fas fa-google"
        url = "https://scholar.google.com/citations?user=hTli1h0AAAAJ&hl"
        weight = 3
    [params.social.researchgate]
        name = "ResearchGate"
        class = "fab fa-researchgate"
        url = "https://www.researchgate.net/profile/Michael-Hahn-26"
        weight = 4
    [params.social.twitter]
        name = "Twitter"
        class = "fab fa-twitter-square"
        url = "https://twitter.com/HahnMic"
        weight = 5


    [params.colors]
        background_color = "#f5f1f0"

[markup.goldmark.renderer]
    unsafe= true


[menu]
    [[menu.main]]
        name = "Publications"
        url = "/publications"
        weight = 1
